interface SortCons {
   final int	MAX_INT = 1000, ARRAY_SIZE = 128, PORTION_SIZE = 10,
		GENERATE = 0, SORT = 1, SHUFFLE = 2, MERGE = 3,
		FLASH_TIMES = 10, FLASH_LENGTH = 50,
		MIN_GAP = 5, LEFT_INSET = 5, RIGHT_INSET = 5,
		TOP_INSET = 40, BOTTOM_INSET = 10;
}
	
